#!/bin/bash

KERNEL_PATH=$PWD
ROOTFS_PATH="$KERNEL_PATH/ramdisk_samsung"
export ARCH=arm
export CROSS_COMPILE=/home/jongwoo/arm-eabi-4.7/bin/arm-eabi-
displayversion=Boeffla-Kernel-5.4-beta1-E210L
export LOCALVERSION="_$displayversion"
make boeffla_defconfig
scripts/configcleaner "
CONFIG_TARGET_LOCALE_USA
CONFIG_TARGET_LOCALE_KOR
CONFIG_MACH_C1_KOR_SKT
CONFIG_MACH_C1_KOR_KT
CONFIG_MACH_C1_KOR_LGT
CONFIG_MACH_M0
CONFIG_SEC_MODEM_M0
CONFIG_SEC_MODEM_C1
CONFIG_SEC_MODEM_C1_LGT
CONFIG_USBHUB_USB3503
CONFIG_UMTS_MODEM_XMM6262
CONFIG_LTE_MODEM_CMC221
CONFIG_IP_MULTICAST
CONFIG_LINK_DEVICE_DPRAM
CONFIG_LINK_DEVICE_USB
CONFIG_LINK_DEVICE_HSIC
CONFIG_IPC_CMC22x_OLD_RFS
CONFIG_SIPC_VER_5
CONFIG_SAMSUNG_MODULES
CONFIG_FM
CONFIG_FM_RADIO
CONFIG_FM_SI4709
CONFIG_FM_SI4705
CONFIG_WLAN_REGION_CODE
CONFIG_LTE_VIA_SWITCH
CONFIG_BRIDGE
CONFIG_FM34_WE395
CONFIG_CDMA_MODEM_CBP72
CONFIG_BRIDGE_NETFILTER
CONFIG_NETFILTER_XT_MATCH_PHYSDEV
CONFIG_BRIDGE_NF_EBTABLES
CONFIG_BRIDGE_IGMP_SNOOPING
CONFIG_DMA_CMA
CONFIG_DMA_CMA_DEBUG
CONFIG_CMA_SIZE_MBYTES
CONFIG_CMA_SIZE_SEL_MBYTES
CONFIG_CMA_SIZE_SEL_PERCENTAGE
CONFIG_CMA_SIZE_SEL_MIN
CONFIG_CMA_SIZE_SEL_MAX
CONFIG_CMA_ALIGNMENT
CONFIG_CMA_AREAS
"
	echo "
# CONFIG_TARGET_LOCALE_USA is not set
CONFIG_TARGET_LOCALE_KOR=y
# CONFIG_MACH_C1_KOR_SKT is not set
# CONFIG_MACH_C1_KOR_KT is not set
CONFIG_MACH_C1_KOR_LGT=y
# CONFIG_MACH_M0 is not set
CONFIG_MACH_C1=y
# CONFIG_SEC_MODEM_M0 is not set
# CONFIG_SEC_MODEM_C1 is not set
CONFIG_SEC_MODEM_C1_LGT=y
CONFIG_MACH_NO_WESTBRIDGE=y
CONFIG_IP_MULTICAST=y
CONFIG_FM34_WE395=y
CONFIG_USBHUB_USB3503=y
# CONFIG_USBHUB_USB3503_OTG_CONN is not set
# CONFIG_UMTS_MODEM_XMM6262 is not set
CONFIG_LTE_MODEM_CMC221=y
CONFIG_LINK_DEVICE_DPRAM=y
CONFIG_LINK_DEVICE_USB=y
# CONFIG_LINK_DEVICE_HSIC is not set
CONFIG_IPC_CMC22x_OLD_RFS=y
CONFIG_SIPC_VER_5=y
# CONFIG_SAMSUNG_MODULES is not set
CONFIG_WLAN_REGION_CODE=203
CONFIG_LTE_VIA_SWITCH=y
CONFIG_BRIDGE=y
CONFIG_CDMA_MODEM_CBP72=y
# CONFIG_FM_RADIO is not set
# CONFIG_FM_SI4709 is not set
# CONFIG_FM_SI4705 is not set
CONFIG_BRIDGE_NETFILTER=y
# CONFIG_NETFILTER_XT_MATCH_PHYSDEV is not set
# CONFIG_BRIDGE_NF_EBTABLES is not set
# CONFIG_BRIDGE_IGMP_SNOOPING is not set
# CONFIG_DMA_CMA is not set
" >> .config
make -j16

echo "Making new boot image"
./mkbootimg --kernel $KERNEL_PATH/arch/arm/boot/zImage --ramdisk $ROOTFS_PATH/boot.img-ramdisk.gz --board smdk4x12 --cmdline 'ttySAC2,115200' --base 0x40000000 --pagesize 2048 -o $KERNEL_PATH/boot.img
